affine_trainable: false
auto_save: true
base_fun_name: identity
ckpt_path: ./composition_model
device: cuda:0
grid: 12
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 1
sb_trainable: true
sp_trainable: true
state_id: '5'
symbolic.funs_name.0:
- - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
symbolic.funs_name.1:
- - x^2
  - x^2
symbolic.funs_name.2:
- - sqrt
symbolic_enabled: true
width:
- - 4
  - 0
- - 2
  - 0
- - 1
  - 0
- - 1
  - 0
